### ISSUE TITLE
deployments missing

### ISSUE THREAD

**Issue by koslib** [getredash/contrib-helm-chart#109]
Followed all steps as any `helm install` chart, as well as after thoroughly go through this chart's readme. Uninstalled and re-installed it dozens of times to confirm I'm not crazy. But I always had this issue: the `genericWorker` and `scheduler` deployments are missing.

The values I use for these are:

```
scheduler:
  replicaCount: 1
  resources:
    limits:
      cpu: 650m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1.5Gi
  nodeSelector:
    dedicatedFor: "management"
  tolerations:
      - effect: NoSchedule 
        key: dedicated
        value: management
        operator: Equal
      - effect: NoExecute
        key: dedicated
        value: management
        operator: Equal
        
 genericWorker:
  replicaCount: 1
  resources:
    limits:
      cpu: 650m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1.5Gi
  nodeSelector:
    dedicatedFor: "management"
  tolerations:
      - effect: NoSchedule 
        key: dedicated
        value: management
        operator: Equal
      - effect: NoExecute
        key: dedicated
        value: management
        operator: Equal
```

Everything else seems to be working fine. Am I the only one with this problem? Any ideas?

**Comment by koslib** [comment]
Started to get a bit deeper in this.

After a succesfull `help repo update`, inspecting the chart (`helm show chart redash/redash`)gives me this:

```
helm show chart redash/redash
apiVersion: v1
appVersion: 8.0.2.b37747
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: ^10.8.2
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: ^8.10.14
description: Redash is an open source tool built for teams to query, visualize and
  collaborate.
home: https://redash.io/
icon: https://redash.io/assets/images/elements/redash-logo.svg
keywords:
- redash
- analytics
- vizualisation
maintainers:
- email: owen.barton@civicactions.com
  name: Owen Barton
name: redash
sources:
- https://github.com/getredash/redash
version: 2.4.0
```

We can see that clearly there is a mismatch of the appversion as well as the version compared to https://github.com/getredash/contrib-helm-chart/blob/master/Chart.yaml. 

Installing/upgrading the chart with version pinning (`helm upgrade -i my-release ..... --version --version 3.0.0-beta1`) works for now. Therefore closing the issue and hope this will help some other soul out there!
