### ISSUE TITLE
install-upgrade.sh STATUS_TIMEOUT is too small, failing upgrade job and helm deployment

### ISSUE THREAD

**Issue by bigman3** [getredash/contrib-helm-chart#117]
Hello

we have encountered a case, where the post install k8s upgrade Job goes into many retries and eventually fails the entire helm installation, due to "STATUS_TIMEOUT" too small.
We have some other workloads running along Redash deployment, so in our use case the return of the status command may take  between 10 and 20 seconds..

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redash.fullname" . }}
  labels:
    {{- include "redash.labels" . | nindent 4 }}
data:
  install-upgrade.sh: |
    #!/usr/bin/env bash
    echo "This will retry connections until PostgreSQL/Redis is up, then perform database installation/migrations as needed."
    # Status command timeout
    STATUS_TIMEOUT=10     <=============================================
```
https://github.com/getredash/contrib-helm-chart/blob/v3.0.0-beta1/templates/configmap.yaml

I suggest increasing this value a bit, 30 seconds maybe ?
I can also support with a PR for this
