### ISSUE TITLE
Unable to disable internal postgreSql database via value.yaml in redash 

### ISSUE THREAD

**Issue by suman20201989** [getredash/contrib-helm-chart#126]
We are working on Redash. For that, we deployed it as a Kubernetes service.  Instead of internal postgreSQL database , we need to use external postgreSQL so we are using our external database .It is working well as expected but i am unable to disable internal PostgreSQL database as i tried to make with below code to make it false but still it create internal Pod of postgreSQL. Can anyone help what is the issue here .For reference attaching snippet which i am using for make it false .

Any help would be highly appreciated

```
spec:
  externalPostgreSQL: EXTERNAL_POSTGRES
  externalPostgreSQLSecret: 
    name: postgres-secret
    key: EXTERNAL_POSTGRES
  postgresql:
    enabled: false        

```

Thanks
