### ISSUE TITLE
Error: failed to download "stable/redash"

### ISSUE THREAD

**Issue by bubilla** [getredash/contrib-helm-chart#14]
Hi everyone.
I am currently trying to install redash on AKS but I always get the following error: Error: failed to download "stable / redash" (hint: running `helm repo update` may help)

I am executing this command:
helm install redash stable / redash

helm repo list
NAME URL
istio.io https://storage.googleapis.com/istio-release/releases/1.3.2/charts/
loki https://grafana.github.io/loki/charts
stable https://kubernetes-charts.storage.googleapis.com

my helm version is 3.0.0

Note that I have already run helm repo update and it doesn't work

Why this error?

**Comment by gabrielmv** [comment]
It's probably because redash doesn't have a chart on helm stable repo yet:

https://github.com/helm/charts/tree/master/stable

**Comment by bubilla** [comment]
So why in the readme does the execution of the "helm install stable / redash" command appear?

Do you know if there is any way to apply Redash in Kubernetes?

**Comment by gabrielmv** [comment]
I cloned this repo to GitLab and installed it on GKE using GitLab CI. But I didn't feel it was very stable. Also I couldn't get email to work

```yaml
.deploy: &deploy
  before_script:
    - echo ${GOOGLE_SERVICE_ACCOUNT_KEY} > google-service-account-key.json
    - /google-cloud-sdk/bin/gcloud auth activate-service-account --key-file google-service-account-key.json
    - /google-cloud-sdk/bin/gcloud container clusters get-credentials ${GCP_CLUSTER_NAME} --zone ${GCP_CLUSTER_ZONE} --project ${GCP_PROJECT_ID}
    - helm init --client-only
    - helm repo update
    - helm dependency update
  script:
    - helm delete ${RELEASE_NAME} --purge
    - >
      helm upgrade ${RELEASE_NAME} . -i --namespace ${NAMESPACE} --values ${VALUES_FILE}
      --set cookieSecret=${COOKIE_SECRET}
      --set externalPostgreSQL=${DATABASE_URL}
      --set postgresql.postgresqlPassword=${DATABASE_PASSWORD}
      --wait
```
