### ISSUE TITLE
Redash mail setup with ses with helm on eks

### ISSUE THREAD

**Issue by mihiran-fc** [getredash/contrib-helm-chart#151]
I'm trying to configure the mail server for redash with ses and the below configuration in my helm chart. I've stored my mail password and username in the `abc-secret`. It's getting deployed successfully but I'm unable to see any of the emails getting triggered for my alerts nor for the invitations. Is there any where I can see the logs related to this mail server in redash to find out what's the issue?
I tried checking the logs for all the pods but it's in vain. I'm able to send test mails from my ses so I think no issues with ses I presume. 
Could you guys please help me if I miss any configuration or how to trouble shoot this issue. 

I tried with port `587` , `2465` and still it didn't work

```
  redash:
    existingSecret: abc-secret
    logLevel: DEBUG
    mailServer: email-smtp.{region}.amazonaws.com
    mailPort: 465
    mailUseTls: true
    mailUseSsl: true
    mailDefaultSender: abc@abc.com
    host: https://abcd.com
```
