### ISSUE TITLE
Issue connecting to any data source

### ISSUE THREAD

**Issue by iRakic** [getredash/contrib-helm-chart#173]
Hello everyone,

I'm using the latest Redash chart (3.0.1).
It was deployed using the following values:
```
ingress:  
  enabled: true  
  ingressClassName: "nginx"
  hosts:
    - host: redash.redacted-domain.tld
      paths:
        - "/"

redash:
  cookieSecret: REDACTED-FOR-SECURITY
  secretKey: REDACTED-FOR-SECURITY

postgresql:
  postgresqlPassword: REDACTED-FOR-SECURITY
redis:
  password: REDACTED-FOR-SECURITY
```

However, when I try to run test for datasource that I have added I get the following error: ""
The /api/data_sources/1/test POST request is responding with HTTP 502 and the execution time is >= 30s

Can you please tell me what is wrong or maybe point me to the right direction?

Thank you in advance!
