### ISSUE TITLE
Can't install with PostgreSQL

### ISSUE THREAD

**Issue by gecube** [getredash/contrib-helm-chart#174]
Good day!

I am trying to install the basic redash with the help of FluxCD. I prepared the basic manifest to achieve it:

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: redash
  annotations:
    openshift.io/requester: system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: redash
  namespace: redash
spec:
  interval: 1h0m0s
  timeout: 1m0s
  url: https://getredash.github.io/contrib-helm-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redash
  namespace: redash
spec:
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: redash
      sourceRef:
        kind: HelmRepository
        name: redash
      version: '*'
  interval: 1m0s
  values:
    serviceAccount:
      create: true
    ingress:
      enabled: false
    postgresql:
      enabled: true
      primary:
        service:
          ports:
            postgresql: 5432
      auth:
        username: redash
        database: redash
```

Then I understood that I need to set up the password for the Postgres instance. As mentioned in the `values.yaml` here: https://github.com/getredash/contrib-helm-chart/blob/e6dce748ba57868277a0ffe59c0c3a802e14a862/charts/redash/values.yaml#L578

But after adding the password I still got the error:

```
Helm install failed for release redash/redash with chart redash@3.0.1: values don't meet the specifications of the schema(s) in the following chart(s): postgresql: - postgresqlPassword: Invalid type. Expected: string, given: null
```

So I went to the bitnami chart and found that the `postgresqlPassword` key is mandatory.

I'd like to ask to correct the chart for redash, add there also `postgresqlPassword` field and prefill both `postgresqlPassword` and `password` keys with some sane default settings.
