### ISSUE TITLE
Helm chart issue: Self managed secrets not propagated to pods

### ISSUE THREAD

**Issue by wfdevopsteam** [getredash/contrib-helm-chart#188]
Hello!

We're setting up Redash using the helmchart provided and using the following value:
```
redash:
  selfManagedSecrets: true
  envSecretName: redash
```
  
 Our secret looks like this:
```
apiVersion: v1
data:
  cookieSecret: <value>
  googleClientSecret: ""
  ldapBindDnPassword: ""
  mailPassword: ""
  secretKey: <value>
kind: Secret
metadata:
```
 Even with this set we keep getting this exception: Exception: You must set the REDASH_COOKIE_SECRET environment variable. Visit http://redash.io/help/open-source/admin-guide/secrets for more information.

Setting the secrets using the "normal" way works, but we don't want to do this since we're version controlling the helm chart values. 

Many thanks in advance!
