### ISSUE TITLE
Template Values.env as an array of object to allow other object format of k8s env

### ISSUE THREAD

**Issue by bzon** [getredash/contrib-helm-chart#27]
I want to add an existing secret as an environment variable for an external postgresql server.

```yaml
    env:
    - name: POSTGRES_PASSWORD 
      valueFrom:
        secretKeyRef:
          name: redash-postgres
          key: password
    # how it will be used..
    externalPostgreSQL: "postgresql://redash:$(POSTGRES_PASSWORD)@postgresql-headless.postgresql:5432/redash"
```

The problem is https://github.com/getredash/contrib-helm-chart/blob/6efbc7cdadbdfae6bde1b7965879f72047dd89f9/templates/server-deployment.yaml#L394-L398
