### ISSUE TITLE
livenessProbe make high CPU

### ISSUE THREAD

**Issue by bangnh1** [getredash/contrib-helm-chart#28]
**Issue Summary**
CPU usage always keep high

**Steps to Reproduce**
Deploy Redash on Kops using helm
All containers reach a Running state.
Capture processes by htop
<img width="1383" alt="Screen Shot 2020-04-02 at 11 58 42" src="https://user-images.githubusercontent.com/29230374/78212609-71d99980-74da-11ea-9952-0f8d640ee8f0.png">

It seems livenessProbe using ./manage.py status for probing

```
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - . /config/dynamicenv.sh && /app/manage.py status
          failureThreshold: 10
          initialDelaySeconds: 90
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
```

**Technical details:**

Redash Version: redash/redash:8.0.2.b37747

Kubernetes version: v1.15.6
Helm version:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
```

**Comment by grugnog** [comment]
@bangnh1 Thanks! We can decrease the periodSeconds for sure, 10s does seem more frequent than necessary. I also wonder if there is a lighter weight way of checking status that we could use.

**Comment by bangnh1** [comment]
I'm checking tcp port 5000 for livenesssProbe.
```
        livenessProbe:
          failureThreshold: 10
          initialDelaySeconds: 90
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5000
          timeoutSeconds: 1
```
