### ISSUE TITLE
Unnecessary required Postgresql password

### ISSUE THREAD

**Issue by leosilvadev** [getredash/contrib-helm-chart#29]
Hello.

I am currently using the Chart but testing the version 2 I am facing the issue of postgresql password required when I am using an external instance, so I am forced to pass a `postgresqlPassword` even though it is not going to be used.

```
redash:
redash:
  cookieSecret: +DkgxNdwbcUZOfDDSDMHMLxSY2Y8YocSfq3bJ602kn8=
  secretKey: XYaeCNrq7RP968foyennRkMYQ3ZieJuecS3D25btGDY=
postgresql:
  enabled: false
  externalPostgreSQL: "postgresql://admin:pwd@localhost:5432/redash"
```

The fix should be easy and I can open a MR for that if needed
