### ISSUE TITLE
Email Configuration on GKE

### ISSUE THREAD

**Issue by gabrielmv** [getredash/contrib-helm-chart#5]
Hello, I'm trying to deploy Redash 8.0.0 on GKE using this chart. So far everything worked, but the email setup

I set the environment variables on the values.yaml like bellow:

```
env:
  PYTHONUNBUFFERED: 0
  REDASH_LOG_LEVEL: "INFO"
  REDASH_HOST: https://redash.myhost.com.br
  REDASH_MAIL_SERVER: smtp.gmail.com
  REDASH_MAIL_PORT: 465
  REDASH_MAIL_USE_TLS: true
  REDASH_MAIL_USE_SSL: true
  REDASH_MAIL_USERNAME: datascience.myhost@gmail.com
  REDASH_MAIL_PASSWORD: "password"
  REDASH_MAIL_DEFAULT_SENDER: datascience.myhost@gmail.com
```

I also tried to use AWS SES, the same configuration worked on another Redash deployment.
