### ISSUE TITLE
Schemas & periodic queues are not processed with Redash V9

### ISSUE THREAD

**Issue by xavier-d** [getredash/contrib-helm-chart#73]
When deploying the latest dockers available (redash/redash:9.0.0-beta.b42121 or redash/redash:preview) the scheduled & schemas jobs are not executed
RQ are well filled but not processed

It is working fine if I'm updating the configuration with the following 

```
adhocWorker:
  # adhocWorker.env -- Redash ad-hoc worker specific envrionment variables.
  env:
    QUEUES: "queries,celery,schemas,periodic"
    WORKERS_COUNT: 2
```
