### ISSUE TITLE
Validation issue when using `externalPostgreSQLSecret`

### ISSUE THREAD

**Issue by z0rc** [getredash/contrib-helm-chart#75]
Sample helmfile (it's wrapper around helm, should be self explanatory)
```
- name: redash
  chart: redash/redash
  version: 2.3.0
  namespace: redash
  values:
  - redash:
      secretKey: supersecretkey
      cookieSecret: cookiesecretkey
    postgresql:
      enabled: false
    externalPostgreSQLSecret:
      name: redash-postgresql
      key: connection-string
    redis:
      enabled: false
    externalRedisSecret:
      name: redash-redis
      key: connection-string
```
Fails on validation with `Error: execution error at (redash/templates/NOTES.txt:26:12): A value for one of the following variables is required: postgresql.postgresqlPassword (secure password), postgresql.existingSecret (secret name), externalPostgreSQL (connection string)`. The workaround is to add valuelike `externalPostgreSQL: "notused"`. Validation logic in https://github.com/getredash/contrib-helm-chart/blob/v2.3.0/templates/NOTES.txt#L26 should probably be updated, or migrated to Helm v3 JSON Schema.
