### ISSUE TITLE
Internal Server Error with Ingress

### ISSUE THREAD

**Issue by deebify** [getredash/contrib-helm-chart#88]
If you setup ingress enabled with redash via load balancer you will get internal server error and from logs in pod. 

`[2021-06-28 09:23:05,737][PID:12][INFO][metrics] method=GET path=/favicon.ico endpoint=redash_index status=302 content_type=text/html; charset=utf-8 content_length=329 duration=0.46 query_count=0 query_duration=0.00
[2021-06-28 09:23:05,842] ERROR in app: Exception on /login [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1610, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1831, in preprocess_request
    rv = func()
  File "/usr/local/lib/python2.7/site-packages/flask_limiter/extension.py", line 400, in __check_request_limit
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/site-packages/flask_limiter/extension.py", line 365, in __check_request_limit
    if not self.limiter.hit(lim.limit, lim.key_func(), limit_scope):
  File "/usr/local/lib/python2.7/site-packages/limits/strategies.py", line 132, in hit
    self.storage().incr(item.key_for(*identifiers), item.get_expiry())
  File "/usr/local/lib/python2.7/site-packages/limits/storage.py", line 446, in incr
    return self.lua_incr_expire([key], [expiry])
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 3575, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 2761, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 772, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 994, in get_connection
    connection.connect()
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 502, in connect
    self.on_connect()
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 570, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 642, in read_response
    raise response
ResponseError: WRONGPASS invalid username-password pair
`

Values file:
```
redash:
  cookieSecret: ##SECRET##
  secretKey: ##SECRET##
postgresql:
  enabled: false
adhocWorker:
  replicaCount: 2
scheduledWorker:
  replicaCount: 2
server:
  replicaCount: 1
externalPostgreSQL: "postgresql://##SECRET##.rds.amazonaws.com:5432/redashdev"
ingress:
   enabled: true
   hosts:
     - host: "*.dev.myapplication.com"
       paths: ["/*"]
   annotations:
     kubernetes.io/ingress.class: alb
     alb.ingress.kubernetes.io/scheme: internet-facing
     alb.ingress.kubernetes.io/certificate-arn: ##SECRET##
     alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
     alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'

service:
   port: 80
   type: NodePort

```
