### ISSUE TITLE
Value can't be overrided

### ISSUE THREAD

**Issue by armandleopold** [getredash/contrib-helm-chart#92]
https://github.com/getredash/contrib-helm-chart/blob/f2a41b74480a4749895b9e72dbf242a658389a02/templates/adhocworker-deployment.yaml#L42

When using as a dependency chart, we can't override the ` .Values.adhocWorker.env` values.

```yaml
          {{- range $key, $value := .Values.adhocWorker.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
          {{- end }}
```

**Comment by grugnog** [comment]
@armandleopold this could use more detail - were you setting adhocWorker.env in your values? What were you setting it to?

**Comment by armandleopold** [comment]
Hello @grugnog  we use the helm chart as a dependency in our helm chart, that way we get a copy of it with our custom values for our organisation.

So the adhocWorker.env are in the "root" values.yaml of our chart in the form of : 

```yaml
redash:
  adhocWorker:
    env:
      <var: null>
```

But there is a know issue with Helm where we cannot nullify a value in our root values.yaml file set by a values.yaml in a dependency chart.
